version: '3.3'

services:
   BCE:
     image: molgor/tutorial-pymc3:latest
     ports:
       - 80:80
       - 8888:8888
       - 8050:8050
     volumes:
       - "./app:/app"
       - "./data/input:/data/input"
       - "./data/output:/data/output" 
       - "./config:/config"
         #restart: always
         #     environment:

       #volumes:
       #    db_data: {}
